# Generated by Django 4.0.3 on 2022-09-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courthouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('court_type', models.CharField(max_length=250)),
                ('court_location', models.CharField(max_length=250)),
                ('number_of_cases_per_day', models.CharField(default=5, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('city_of_origin', models.CharField(max_length=250)),
                ('role', models.CharField(max_length=250)),
                ('court_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.courthouse')),
            ],
        ),
        migrations.AddField(
            model_name='courthouse',
            name='users',
            field=models.ManyToManyField(to='court.user'),
        ),
    ]
