# Generated by Django 4.0.3 on 2022-09-20 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0003_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCaseDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=250)),
                ('created_on', models.CharField(max_length=250)),
                ('type', models.CharField(max_length=250)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.case')),
                ('courthouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.courthouse')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='court.user')),
            ],
        ),
    ]
